#
#   Author: Rohith
#   Date: 2015-04-22 15:01:18 +0100 (Wed, 22 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: downloading the etcd binary
  sudo: yes
  get_url: url="{{ etcd_release }}" dest=/opt/etcd.tar.gz mode=0400
  tags: etcd

- stat: path="/opt/etcd-{{ etcd_version }}-linux-amd64"
  register: extracted
  tags: etcd

- name: extract the etcd binary
  sudo: yes
  unarchive: src=/opt/etcd.tar.gz dest=/opt copy=no
  when: extracted.stat.exists == False
  tags: etcd

- name: create a etcd distribution links
  sudo: yes
  file: src="/opt/etcd-{{ etcd_version }}-linux-amd64/{{ item }}" dest="/usr/bin/{{ item }}" state=link force=yes
  with_items:
    - etcd
    - etcdctl
  tags: etcd

