#
#   Author: Rohith
#   Date: 2015-04-24 15:22:49 +0100 (Fri, 24 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: creating the marathon configuration directory
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0550
  with_items:
    - /config/marathon
  tags:
    - marathon

- name: add the marathon unit file
  sudo: yes
  template: src=marathon.service.j2 dest={{ systemd_dir }}/marathon.service
  notify:
    - reload services
    - restart marathon
  tags:
    - marathon

- meta: flush_handlers

- name: enable and start marathon
  sudo: yes
  service: enabled=yes name=marathon state=started
  tags:
    - marathon

#- name: copy nginx configuration
#  sudo: yes
#  template:
#    src: marathon.nginx.j2
#    dest: /etc/marathon/marathon.nginx
#  notify:
#    - restart nginx-marathon
#  tags:
#    - marathon
#
#- name: configure nginx
#  sudo: yes
#  command: curl -X PUT -d @/etc/marathon/marathon.nginx localhost:8500/v1/kv/service/nginx/templates/marathon
#  tags:
#    - marathon
#
#- name: configure nginx-marathon
#  sudo: yes
#  template:
#    src: nginx-marathon.service.j2
#    dest: /usr/lib/systemd/system/nginx-marathon.service
#  notify:
#    - restart nginx-marathon
#  tags:
#    - marathon
#
#- name: enable nginx-marathon
#  sudo: yes
#  service:
#    name: nginx-marathon
#    enabled: yes
#    state: started
#  notify:
#    - restart nginx-marathon
#  tags:
#    - marathon

