#
#   Author: Rohith
#   Date: 2015-05-02 12:22:23 +0100 (Sat, 02 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

kubernetes_binaries:
  - kube-apiserver
  - kube-controller-manager
  - kubectl
  - kubelet
  - kube-proxy
  - kubernetes
  - kube-scheduler

