#
#   Author: Rohith
#   Date: 2015-04-27 11:17:25 +0100 (Mon, 27 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- file: path=/config/bastion state=directory mode=0770

- name: adding the ssh keys
  authorized_key: 
    path: /config/bastion/authorized_keys
    user: root 
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - public_keys/*
  tags: bastion

- name: create the bastion service fleet unit
  delegate_to: "{{ fleet_delegation }}"
  template: 
    src:  bastion.service.j2
    dest: /config/bastion/bastion.service
  register: service_file 
  tags: bastion

- name: restarting the bastion service 
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  fleet:
    command: stop 
    unit: bastion.service 
  when: service_file.changed
  tags: bastion

- name: deploy the bastion service via fleet
  delegate_to: "{{ fleet_delegation }}"
  fleet:
    command: start
    unit: /config/bastion/bastion.service
  tags: bastion
