#
#   Author: Rohith
#   Date: 2015-04-27 11:17:25 +0100 (Mon, 27 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- file: path=/home/bastion/.ssh state=directory mode=0550

- name: adding the bastion ssh keys
  template: 
    src: id_rsa.j2
    dest: "/root/.ssh/{{ item.name }}"
    mode: 0400
  with_items: "{{ bastion_keys }}"

- name: adding the bastion public ssh key
  copy: 
    src: files/bastion.pub
    dest: /root/.ssh/id_rsa.pub
    mode: 0400

