#
#   Author: Rohith
#   Date: 2015-05-03 12:59:46 +0100 (Sun, 03 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: adding the docker mirror options
  template:
    src: docker-mirror.j2
    dest: /etc/sysconfig/docker-mirror
    mode: 0444
  notify:
    - reload services
    - restart docker
  tags:
    - docker-mirror
    - docker
  when: groups[docker_mirror_group]

- meta: flush_handlers
