#
#   Author: Rohith
#   Date: 2015-04-24 15:22:49 +0100 (Fri, 24 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create consul directories
  sudo: yes
  file: path=/config/consul state=directory mode=0550
  tags: consul

- set_fact:
    consul_binary: /usr/bin/docker exec -ti consul consul
  tags: consul

- set_fact:
    consul_binary: /opt/consul/bin/consul
  when: consul_native
  tags: consul

- name: consul configuration
  sudo: yes
  template: src=consul.json.j2 dest=/config/consul/consul.json mode=0440
  notify:
    - reload services
    - restart consul
  register: consul_changed
  tags: consul

- include: consul_native.yml
  sudo: yes
  when: consul_native
  tags: consul

- include: consul_docker.yml
  sudo: yes
  when: consul_native == false
  tags: consul

- name: stop consul
  sudo: yes
  service: name=consul state=stopped
  when: consul_changed|changed

- name: ensure the consul service
  service: name=consul enabled=yes state=started
  tags: consul

- name: wait for consul available on port 8300 for clustering
  wait_for:
    port: 8300
    state: present
    host: "{{ consul_advertise }}"
    timeout: 120

- name: provision new encription key
  sudo: yes
  command: "{{ consul_binary }} keyring -install={{consul_encryption_key}}"
  when: consul_encryption_key is defined
  tags: consul

- name: use new encription key
  sudo: yes
  command: "{{ consul_binary }} keyring -use={{consul_encryption_key}}"
  when: consul_encryption_key is defined
  tags: consul

- name: join consul in a cluster
  sudo: yes
  command: "{{ consul_binary }} join {{ consul_retry_join }}"
  when: consul_changed is defined
  tags: consul

- name: wait for consul on port 8500
  wait_for:
    port: 8500
    host: "{{ consul_advertise }}"
    state: present
    timeout: 120
  tags: consul
