#
#   Author: Rohith
#   Date: 2015-05-12 14:37:45 +0100 (Tue, 12 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

gluster_group: gluster
gluster_fleet_tag: gluster
gluster_bricks_dir: /srv/gluster/
gluster_image: humble/fed20-gluster
gluster_image_tag: latest

