#
#   Author: Rohith
#   Date: 2015-04-23 16:35:42 +0100 (Thu, 23 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- hosts: localhost
  gather_facts: false
  tasks:
    - include_vars: sites/sbx/vars/sbx.yml

- hosts: "{{ hostname }}"
  gather_facts: false
  roles:
    - { role: vagrant, when: "is_coreos == false" }