#
#   Author: Rohith
#   Date: 2015-02-26 20:13:31 +0000 (Thu, 26 Feb 2015)
#
#  vim:ts=2:sw=2:et
#

- name: "include the location specifics"
  hosts: all
  tasks:
    - include_vars: "vars/location/{{ location | mandatory}}.yml"
    - include_vars: "vars/os.yml"
    - include: "vars/facts/main.yml"
  roles:
    - common/environment
  tags: location

- hosts: all
  gather_facts: false
  roles:
    - common/hosts
    - common/resolver
    - common/distro
    - common/ntp
    - common/bash
    - common/ssh_keys
    - configdir

- hosts: bastion
  gather_facts: false
  roles:
    - bastion

- hosts: docker-cache
  gather_facts: false
  roles:
    - docker/engine
    - docker/cache

- hosts: glusterfs_servers
  gather_facts: false
  vars:
    gluster_server_group: glusterfs_servers
  roles:
    - glusterfs/server

- hosts: mesos_slaves
  gather_facts: false
  vars:
    gluster_server_group: glusterfs_servers
    gluster_mounted_volumes:
      - name: default
        directory: /glusterfs
  roles:
    - { role: glusterfs/client, when: "groups['glusterfs_servers']" }

- hosts: mesos_slaves
  gather_facts: false
  roles:
    - docker/engine
    - { role: docker/mirror, when: "groups['docker-cache']" }

- hosts: zookeeper_servers
  gather_facts: false
  vars:
    zookeeper_network_mode: bridge
  roles:
    - zookeeper

- hosts: mesos
  gather_facts: false
  roles:
    - mesos

- hosts: mesos_slaves
  gather_facts: false
  sudo: yes
  vars:
    marathon_zookeeper_group: zookeeper_servers
    etcd_servers_group: mesos_slaves
    etcd_dockerized: true
  roles:
    - marathon
    - etcd
    - { role: registrator, registrator_service: registrator_consul, registrator_backend: 'consul://${PRIVATE_IP}:8500' }
    - { role: registrator, registrator_service: registrator_etcd,   registrator_backend: '-ip ${PRIVATE_IP} etcdex://${PRIVATE_IP}:4001/services' }
    - embassy
