#
#   Author: Rohith
#   Date: 2015-05-02 12:27:29 +0100 (Sat, 02 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: ensure the virt-release repository
  sudo: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    mode: 0444
  with_items:
    - virt.repo
  tags: docker

- name: install docker package
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - device-mapper-event-libs
    - "docker-{{ centos_docker_version }}"
  tags: docker

- copy:
    src: docker.service
    dest: "{{ systemd_dir }}/docker.service"
  notify:
    - restart docker
  tags: docker

- name: create service override directory
  file: path="{{ systemd_dir }}/docker.service.d" state=directory mode=0755

