#
#   Author: Rohith
#   Date: 2015-04-24 15:22:49 +0100 (Fri, 24 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

provider: vcloud
environment: dev
dns_zone: example.com
dns_region: dev
dns_base: "{{ dns_region }}.{{ dns_zone }}"
dns_ttl: 90
dns_servers:
  - 8.8.8.8
  - 8.8.4.4
timezone: UTC
ntp_servers:
  - 0.uk.pool.ntp.org
  - 1.uk.pool.ntp.org
  - 2.uk.pool.ntp.org
  - 3.uk.pool.ntp.org

## KUBERNETES ============================
kubernetes_overlay_network: 10.101.0.0
kubernetes_overlay_prefix: 16
kubernetes_subnets: 24
kubernetes_subnets_min: 10.101.1.0
kubernetes_subnets_max: 10.101.50.0
kubernetes_backend: vxlan

## WEAVE =================================
weave_network: 10.101.0.0
weave_network_mask: 16
weave_nodeid: "{{ ansible_hostname | regex_replace('[a-zA-Z]*', '') }}"
weave_network_ip: "10.101.0.{{ weave_nodeid }}/{{ weave_network_mask }}"
weave_cidr_mask: 24
weave_cidr: "10.101.{{ weave_nodeid }}.0/{{ weave_cidr_mask }}"
weave_group: mesos

## REGION MAPPING ========================
regions_mapping:
  dev:
    vdc: DEV_TEST (IL2-DEVTEST-BASIC)
    description: 'Common Docker Services'

    os:
      centos: ami-e4ff5c93
      coreos: ami-57950a20
    networks:
      web:
        name: COMMON_DOCKER_SERVICES
        fence_mode: natRouted
        edge_gateway: 'nft001cfi2'
        is_shared: false
        gateway: 10.7.20.1
        netmask: 255.255.255.240
        dns_suffix: docker.dev.hod.homeoffice.gov.uk
        start_address: 10.7.20.2
        end_address: 10.7.20.14

sku_models:
  small: vapp_small
  medium: vapp_medium
  large: m1.large
  xlarge: m2.large

