#
#   Author: Rohith
#   Date: 2015-05-02 12:57:11 +0100 (Sat, 02 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

groups:
  - name: bastion
    hosts: bastion101

  - name: coreos
    hosts: (.*)[0-9]{1,3}

  - name: core
    hosts: core[0-9]{1,3}

  - name: ceph
    hosts: store[0-9]{1,3}

  - name: ceph-monitor
    hosts: store[0-9]{1,3}

  - name: ceph-osd
    hosts: store[0-9]{1,3}

  - name: docker
    hosts: docker

  - name: docker-cache
    hosts: cache[0-9]{1,3}

  - name: gluster
    hosts: gluster[0-9]{1,3}

  - name: openvpn_servers
    hosts: openvpn[0-9]{1,3}

  - name: kubernetes-master
    hosts: (master101|core101)

  - name: kubernetes-minion
    hosts: core[0-9]{1,3}

  - name: kubernetes
    groups:
      - kubernetes-master
      - kubernetes-minion

