#
#   Author: Rohith
#   Date: 2015-04-23 16:35:42 +0100 (Thu, 23 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: add our ssh key for provisioning
  authorized_key:
    user: root
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    path: '/root/.ssh/authorized_keys'
    manage_dir: yes
