#
#   Author: Rohith
#   Date: 2015-05-06 10:51:26 +0100 (Wed, 06 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- hosts: coreos
  gather_facts: false
  roles:
    - coreos/bootstrap

- hosts: all
  gather_facts: true
  tasks:
    - include_vars: "vars/dev.yml"
    - include_vars: "vars/bastion.key.yml"
    - include_vars: "../../vars/facts/os.yml"
    - include: "../../vars/facts/main.yml"
  tags: location

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - common/environment
  tags: location

- hosts: bastion
  gather_facts: true
  roles:
    - bastion
    - dhcpd
    - docker/engine
    - docker/mirror
    - fleet/client
    - { role: kubernetes/client, when: "groups[kubernetes_master_group]" }

- hosts: coreos
  gather_facts: false
  roles:
    - coreos/cloudinit

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - common/hosts
    - common/resolver
    - common/distro
    - common/ntp
    - common/bash
    - common/ssh_keys
    - common/configdir

- hosts: glusterfs_servers
  gather_facts: false
  roles:
    - glusterfs/server

- hosts: kubernetes_master
  gather_facts: false
  sudo: yes
  roles:
    - docker/engine
    - docker/mirror
    - flannel/config
    - flannel/flanneld
    - kubernetes/master
    - kubernetes/gluster

- hosts: kubernetes_minion
  gather_facts: false
  sudo: yes
  roles:
    - flannel/flanneld
    - kubernetes/minion
