#
#   Author: Rohith
#   Date: 2015-05-18 14:40:31 +0100 (Mon, 18 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

gateway_ip: "{{ hostvars[inventory_hostname]['ansible_' + iface].ipv4.address }}"
gateway_image: gambol99/haproxy
gateway_image_tag: latest
service_name: gateway
