#
#   Author: Rohith
#   Date: 2015-05-10 18:38:32 +0100 (Sun, 10 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

zookeeper_image: jplock/zookeeper
zookeeper_image_tag: 3.4.6

zookeeper_network_mode: bridge
zookeeper_service: zookeeper
zookeeper_service_tags: "{{ zookeeper_service }}"
zookeeper_ensemble: cluster1
zookeeper_container_name: "{{ zookeeper_service }}"
zookeeper_data_volume: "{{ zookeeper_service }}-data-volume"
zookeeper_server_group: zookeeper_servers
zookeeper_id: "
  {%- if zk_id is defined -%}
    {{ zk_id }}
  {%- else -%}
    {%- for host in groups[zookeeper_server_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
  {%- endif -%}"

