#
#   Author: Rohith
#   Date: 2015-05-03 15:33:08 +0100 (Sun, 03 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: restart kubernetes proxy
  sudo: yes
  shell: /bin/systemctl restart kubernetes-proxy

- name: restart kubernetes kubelet
  sudo: yes
  shell: /bin/systemctl restart kubernetes-kubelet
