#
#   Author: Rohith
#   Date: 2015-05-02 12:22:23 +0100 (Sat, 02 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: creating the kubernetes config directory
  file: path=/config/kubernetes state=directory mode=0550
  tags: 
    - kubernetes
    - kubernetes-common
