#
#   Author: Rohith
#   Date: 2015-05-04 22:40:08 +0100 (Mon, 04 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- yum: name=ntp state=present
  tags: 
    - common
    - ntp

- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes
  tags: 
    - common
    - ntp
