#
#   Author: Rohith
#   Date: 2015-05-04 22:41:19 +0100 (Mon, 04 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

#- service: name=settimezone state=started enabled=yes
#  tags: 
#    - common
#    - ntp

- name: create the local ntp config
  shell: touch /etc/ntp.conf.coreos
  sudo: yes 

- name: setup nginx sites-available symlink
  file: 
    path: /etc/ntp.conf 
    src: /etc/nto.conf.coreos 
    state: link 
    force: yes
