#
#   Author: Rohith
#   Date: 2015-05-27 23:02:11 +0100 (Wed, 27 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

kubernetes_version: 0.16.1
kubernetes_release: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64"
