#
#   Author: Rohith
#   Date: 2015-05-18 14:40:40 +0100 (Mon, 18 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the http_router config directory
  file: path=/config/http_router state=directory mode=0550
  tags: http_router

- name: add the http_router systemd service
  template:
    src: http_router.service.j2
    dest: "{{ systemd_dir }}/{{ service_name }}.service"
  notify: 
    - reload services
    - restart http_router
  tags: http_router

- name: drop in http_router config
  copy:
    src: nginx.conf.tmpl
    dest: /config/http_router/nginx.conf.tmpl
    mode: 0440
  notify: 
    - reload services
    - restart http_router
  tags: http_router

- meta: flush_handlers

- name: ensure http_router service
  service: name={{ service_name }} state=started enabled=yes
  tags: http_router

