#
#   Author: Rohith
#   Date: 2015-04-22 15:31:53 +0100 (Wed, 22 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the mesos configuration directory
  file:
    path: /config/mesos/master
    state: directory
    mode: 0550
  tags:
    - mesos
    - mesos-master

- name: add the master credentials file
  template:
    src: master-credentials.j2
    dest: /config/mesos/master/credentials
    mode: 0440
  tags:
    - mesos
    - mesos-master

- name: deploy the mesos master systemd unit
  sudo: yes
  template:
    src: mesos-master.service.j2
    dest: {{ systemd_dir }}/mesos-master.service
    mode: 0440
  notify:
    - reload services
    - restart mesos master
  tags:
    - mesos
    - mesos-master

- meta: flush_handlers

- name: ensure the mesos-master service
  service: name=mesos-master enabled=yes state=started
  tags:
    - mesos
    - mesos-master
