#
#   Author: Rohith
#   Date: 2015-04-22 15:31:53 +0100 (Wed, 22 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the mesos slave environment
  sudo: yes
  file:
      path: /config/mesos/slave
      state: directory
      mode: 0550
  tags:
      - mesos
      - mesos-slave

- name: add mesos slave configuration
  sudo: yes
  copy:
      content: "{{ item.content }}"
      dest: "/config/mesos/slave/{{ item.dest }}"
  notify: restart mesos slave
  with_items:
    - dest: containerizers
      content: "docker"
    - dest: executor_registration_timeout
      content: "{{ mesos_executor_registration_timeout }}"
    - dest: resources
      content: "{{ mesos_resources }}"
    - dest: attributes
      content: "node_id:{{ inventory_hostname }}"
    - dest: hostname
      content: "{{ public_ip }}"
  tags:
      - mesos-slave

- name: deploy the mesos slave systemd unit
  sudo: yes
  template:
    src: mesos-slave.service.j2
    dest: {{ systemd_dir }}/mesos-slave.service
    mode: 0440
  notify:
    - reload services
    - restart mesos slave
  tags:
    - mesos-slave

- meta: flush_handlers

- name: ensure the mesos-slave service
  service:
    name: mesos-slave
    enabled: yes
    state: started
  tags:
    - mesos-slave
