#
#   Author: Rohith
#   Date: 2015-04-22 15:01:18 +0100 (Wed, 22 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- include: dockerized.yml
  when: etcd_dockerized

- include: nondockerized.yml
  when: etcd_dockerized == false

- debug: var="{{ etcd_servers_group }}"
  tags: etcd

- name: etcd profile.d
  sudo: yes
  template: src=etcd.sh.j2 dest=/etc/profile.d/etcd.sh mode=0555
  tags: etcd

- name: restart etcd services
  sudo: yes
  shell: /bin/systemctl daemon-reload; /bin/systemctl restart etcd
  when: etcd_changed | changed and etcd_client_only == false
  tags: etcd

- name: enable and start etcd
  sudo: yes
  service: enabled=yes name=etcd state=started
  when: etcd_client_only == false
  tags: etcd
