#
#   Author: Rohith
#   Date: 2015-05-10 19:00:38 +0100 (Sun, 10 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

mesos_master_image: mesosphere/mesos-master
mesos_slave_image: mesosphere/mesos-slave
mesos_master_image_tag: 0.20.1
mesos_slave_image_tag: 0.20.1

mesos_mode: follower
mesos_log_dir: /var/log/mesos
mesos_work_dir: /var/run/mesos
mesos_leader_port: 15050
mesos_leader_proxy_port: 5050
mesos_follower_port: 5051
mesos_leader_cmd: mesos-master
mesos_follower_cmd: mesos-slavemesosphere/marathon
mesos_executor_registration_timeout: 10mins
mesos_resources: "ports(*):[4000-5000, 31000-32000]"
mesos_cluster: cluster1


mesos_zookeeper_group: zookeeper_servers
mesos_zookeeper_servers: "{{ groups[mesos_zookeeper_group] | sort }}"
mesos_zookeeper_url: "{% for host in mesos_zookeeper_servers %}{{ hostvars[host]['ansible_' + iface].ipv4.address }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

mesos_zk_auth: "{% if zk_mesos_user_secret is defined %}{{ zk_mesos_user }}:{{ zk_mesos_user_secret }}@{% endif %}"
mesos_zk_dns: "zookeeper.service.{{ consul_dns_domain }}"
mesos_zk_port: 2181
mesos_zk_chroot: mesos
mesos_zk_acl_world: "world:anyone:r"
mesos_zk_acl: "{% if zk_mesos_user_secret is defined %}digest:{{ zk_mesos_user }}:{{ zk_mesos_user_secret_digest}}:cdraw{% endif %}"
mesos_zk_acl_cmd: "docker run --rm -e ZK_AUTH=super:{{ zk_super_user_secret }} -e ZNODE=/{{ mesos_zk_chroot }} -e ZNODE_ACL={{ mesos_zk_acl_world }},{{ mesos_zk_acl }} -e ZK_SERVER={{ mesos_zk_dns }}:{{ mesos_zk_port }} --entrypoint /usr/local/bin/setacl.sh {{ zk_docker_image }}"

mesos_authentication: true

mesos_credentials:
  - principal: mesos-admin
    secret: kodad9qa3jf2=0t8sdgvsd_

mesos_authenticate_frameworks: "{{ mesos_credentials|length > 0 }}"
mesos_authenticate_followers: "{{ mesos_follower_secret != '' }}"
mesos_follower_principal: follower
mesos_follower_secret: ""

public_ip: "{{ hostvars[inventory_hostname]['ansible_' + iface].ipv4.address }}"

