#
#   Author: Rohith
#   Date: 2015-05-03 13:02:26 +0100 (Sun, 03 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: adding the kubernetes token authenication
  template: src=kubernetes-token-auth.j2 dest="/config/kubernetes/{{ kubernetes_token_filename }}" mode=0400
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-api
    - kubernetes-tokens
  when: kubernetes_token_auth is defined
  
- name: create the api fleet unit
  delegate_to: "{{ fleet_delegation }}"
  run_once: true
  template: 
    src:  kubernetes-api.service.j2
    dest: /config/kubernetes/kubernetes-api.service
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-api

- name: starting the api service via fleet
  delegate_to: "{{ fleet_delegation }}"
  run_once: true
  shell: fleetctl start /config/kubernetes/kubernetes-api.service
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-api

- name: create the api presence unit
  delegate_to: "{{ fleet_delegation }}"
  run_once: true
  template: 
    src:  kubernetes-api-presence.service.j2
    dest: /config/kubernetes/kubernetes-api-presence.service
  tags: 
    - kubernetes
    - kubernetes-api
    - kubernetes-master
    - kubernetes-api-presence

- name: starting the api presence service via fleet
  delegate_to: "{{ fleet_delegation }}"
  run_once: true
  shell: fleetctl start /config/kubernetes/kubernetes-api-presence.service
  tags: 
    - kubernetes
    - kubernetes-api
    - kubernetes-master
    - kubernetes-api-presence
    
