#
#   Author: Rohith
#   Date: 2015-05-03 13:02:26 +0100 (Sun, 03 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: adding the kubernetes token authenication
  template: src=kubernetes-token-auth.j2 dest="/config/kubernetes/{{ kubernetes_token_filename }}" mode=0400
  tags: 
    - kubernetes
    - kubernetes-api
    - kubernetes-tokens
  when: kubernetes_token_auth is defined

- name: generate the service units
  delegate_to: "{{ fleet_delegation }}"
  run_once: true
  template:
    src: "{{ item }}.j2"
    dest: "/config/kubernetes/{{ item }}"
    mode: 0440
  with_items:
    - kubernetes-api.service
    - kubernetes-api-presence.service
  tags: kubernetes-api

- name: submitting the kubernetes-api services via fleetctl
  delegate_to: "{{ fleet_delegation }}"
  run_once: true
  fleet:
    command: start 
    unit: "/config/kubernetes/{{ item }}"
  with_items:
    - kubernetes-api.service
    - kubernetes-api-presence.service
  tags: kubernetes-api  
