#
#   Author: Rohith
#   Date: 2015-05-21 20:27:07 +0100 (Thu, 21 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: adding some useful tools for the master
  yum: name={{ item }} state=present 
  with_items:
    - git
  tags: 
    - kubernetes
    - kubernetes-master
    - packages
