#
#   Author: Rohith
#   Date: 2015-05-03 13:02:26 +0100 (Sun, 03 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the controller fleet unit
  delegate_to: "{{ fleet_delegation }}"
  template: 
    src:  kubernetes-controller.service.j2
    dest: /config/kubernetes/kubernetes-controller.service
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-controller

- name: starting the controller service via fleet
  delegate_to: "{{ fleet_delegation }}"
  sudo: yes
  shell: fleetctl --endpoint="{{ fleet_endpoints }}" start /config/kubernetes/kubernetes-controller.service
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-controller
