#
#   Author: Rohith
#   Date: 2015-05-03 13:02:26 +0100 (Sun, 03 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the scheduler fleet unit
  template: 
    src:  kubernetes-scheduler.service.j2
    dest: /config/kubernetes/kubernetes-scheduler.service
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-scheduler
  when: fleet_deployed

- name: starting the scheduler service via fleet
  delegate_to: "{{ fleet_delegation }}"
  fleet: 
    command: start
    endpoint: "http://{{ fleet_endpoint }}:4001"
    unit: /config/kubernetes/kubernetes-scheduler.service
  register: result
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-scheduler
  when: fleet_deployed

- name: adding the kubernetes scheduler service
  template: src=kubernetes-scheduler.service.j2 dest={{ systemd_dir }}/kubernetes-scheduler.service 
  notify:
    - reload services
    - restart kubernetes scheduler
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-scheduler
  when: fleet_deployed == false

- meta: flush_handlers

- name: start the kubernetes scheduler service
  service: name=kubernetes-scheduler state=started enabled=yes
  tags: 
    - kubernetes
    - kubernetes-master
    - kubernetes-scheduler
  when: fleet_deployed == false
