#
#   Author: Rohith
#   Date: 2015-04-23 00:49:42 +0100 (Thu, 23 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

default_coreos_virtualbox: &COREOSBOX_DEFAULT
  box: "coreos-alpha"
  url: "http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"
  cloudinit: 'roles/vagrant/templates/cloudinit.coreos.virtualbox.erb'
  gui: false
  resources:
    cpus: 2
    memory: 2048
    biosbootmenu: disabled

default_coreos_virtualbox: &COREOS_STORE_BOX_DEFAULT
  <<: *COREOSBOX_DEFAULT
  resources:
    cpus: 1
    memory: 1024
    biosbootmenu: disabled

boxes:
  store101.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.53
      disks:
      - name: docker
        size: 8192
      - name: ceph
        size: 8192
    fleet:
       ceph_monitor: true
       ceph_osd: true
  store102.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.54
      disks:
      - name: docker
        size: 8192
      - name: ceph
        size: 8192
    fleet:
       ceph_monitor: true
       ceph_osd: true
  store103.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.55
      disks:
      - name: docker
        size: 8192
      - name: ceph
        size: 8192
    fleet:
       ceph_monitor: true
       ceph_osd: true
  gluster101.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.57
      disks:
      - name: docker
        size: 8192
      - name: gluster
        size: 8192
    fleet:
      gluster: true
  gluster102.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.58
      disks:
      - name: docker
        size: 8192
      - name: gluster
        size: 8192
    fleet:
      gluster: true
  bastion101.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.61
    fleet:
      kubernetes: true
      role: bastion
  core101.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.203
      disks:
      - name: docker
        size: 8192
    fleet:
      kubernetes: true
      role: minion
  core102.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.204
      disks:
      - name: docker
        size: 8192
    fleet:
      kubernetes: true
      role: minion
  cache101.sbx.example.com:
    virtualbox:
      <<: *COREOSBOX_DEFAULT
      ip: 10.250.1.240
      disks:
      - name: docker
        size: 8192
