#
#   Author: Rohith
#   Date: 2015-05-12 23:17:10 +0100 (Tue, 12 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: configure gluster peers
  shell: /usr/bin/docker exec -ti gluster gluster peer probe {{ item }}
  with_items: groups[gluster_group]
  when: inventory_hostname == "{{ groups[gluster_group][0] }}"
  tags: gluster
