#
#   Author: Rohith
#   Date: 2015-05-12 14:34:10 +0100 (Tue, 12 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- file: path=/config/gluster state=directory mode=0550
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  tags: gluster

- name: create the gluster proxy fleet unit
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  template: 
    src:  gluster.service.j2
    dest: /config/gluster/gluster.service
  tags: gluster

- name: starting the gluster service via fleet
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  sudo: yes
  shell: fleetctl start /config/gluster/gluster.service
  tags: gluster
