#
#   Author: Rohith
#   Date: 2015-04-29 15:44:00 +0100 (Wed, 29 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- hosts: localhost
  gather_facts: false
  sudo: no  
  tasks:    
    - name: "wait for the box {{ item }} to bootstrap"
      shell: while ! timeout 1 bash -c "echo > /dev/tcp/{{ item }}/2023"; do sleep 0.5; done
      with_items: groups['coreos']
    
- hosts: all
  gather_facts: true
  vars:
    bastion_hostname: "{{ bastion | default('core101') }}"
  tasks:
    - include_vars: "vars/{{ location | mandatory }}.yml"
    - include_vars: "vars/{{ location | mandatory }}.discovery.yml"
    - include_vars: "../../vars/facts/os.yml"
    - include: "../../vars/facts/main.yml"
    - set_fact: bastion_host="{{ bastion_hostname }}"
  tags: location

- hosts: all
  gather_facts: false
  roles:
    - common/bash
    - common/configdir
  tags: common

- hosts: all
  gather_facts: false
  roles:
    - kubernetes/master
    - kubernetes/minion
