#
#   Author: Rohith
#   Date: 2015-04-29 15:44:00 +0100 (Wed, 29 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- hosts: all
  gather_facts: true
  sudo: yes
  tasks:
    - include_vars: "../../vars/location/develop.yml"
    - include_vars: "../../vars/location/sbx.discovery.yml"
    - include_vars: "../../vars/facts/os.yml"
    - include: "../../vars/facts/main.yml"
  roles:
    - common/environment
  tags: location

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - common/hosts
    - common/resolver
    - common/distro
    - common/ntp
    - common/bash
    - common/ssh_keys
    - common/configdir

- hosts: glusterfs_servers
  gather_facts: false
  vars:
    gluster_server_group: glusterfs_servers
  roles:
    - glusterfs/server

- hosts: all
  gather_facts: false
  sudo: yes
  vars:
  roles:
    - docker/engine
    - docker/mirror
    - flannel/config
    - flannel/flanneld
    - kubernetes/master

- hosts: all
  gather_facts: false
  sudo: yes
  vars:
  roles:
    - flannel/flanneld
    - kubernetes/minion
    - kubernetes/gluster
