#
#   Author: Rohith
#   Date: 2015-04-29 15:44:00 +0100 (Wed, 29 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

- hosts: localhost
  gather_facts: false
  sudo: no  
  tasks:    
    - name: wait for the box to bootstrap
      shell: while ! timeout 1 bash -c "echo > /dev/tcp/{{ item }}/2023"; do sleep 0.3; done
      with_items: groups['coreos']

- hosts: all
  gather_facts: true
  tasks:
    - include_vars: "vars/{{ location }}.yml"
    - include_vars: "../sbx/vars/sbx.discovery.yml"
    - include_vars: "../../vars/facts/os.yml"
    - include: "../../vars/facts/main.yml"
  tags: location

- hosts: all
  gather_facts: false
  vars: 
    fleet_delegation: "core101.{{ dns_base }}"
  roles:
    - common/bash
    - common/configdir
    - bastion
    - kubernetes/common
    - kubernetes/master
    - kubernetes/minion
  tags: 
    - kubernetes
    - bastion
    - common
