#
#   Author: Rohith
#   Date: 2015-05-02 12:22:23 +0100 (Sat, 02 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

kubernetes_version: 0.16.1
kubernetes_release: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version}}/bin/linux/amd64"
kubernetes_dir: /opt/kubernetes
kubernetes_binaries:
  - kube-apiserver
  - kube-controller-manager
  - kubectl
  - kubelet
  - kube-proxy
  - kubernetes
  - kube-scheduler

kubernetes_cluster_name: "kube-{{ location }}"
kubernetes_master_hostname: "{{ groups['kubernetes_master'][0] }}"
kubernetes_master_ip: "{{ hostvars[kubernetes_master_hostname].ansible_env['PRIVATE_IP'] }}"
kubernetes_minion_group: kubernetes_minion
kubernetes_minion_servers: "{% for host in groups[kubernetes_minion_group] %}{{ hostvars[host].ansible_env['PRIVATE_IP'] }}{% if not loop.last %},{% endif %}{% endfor %}"

## - Networking - ##
kube_service_addresses: 10.250.1.0/24
dns_setup: true
dns_domain: kube.local
dns_server: 10.254.0.10

fleet_deployed: false
