#
#   Author: Rohith
#   Date: 2015-05-27 23:02:11 +0100 (Wed, 27 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: download the kubernetes binaries
  get_url:
    url: "{{ kubernetes_release }}/{{ item }}"
    dest: "/opt/kubernetes-{{ kubernetes_version }}/{{ item }}"
    mode: 0555
    timeout: 120
  with_items: "{{ kubernetes_binaries }}"
  tags: 
    - kubernetes
    - kubernetes-common

- name: mapping the release into platform
  file:
    src: "/opt/kubernetes-{{ kubernetes_version }}/{{ item }}"
    dest: "{{ kubernetes_dir }}/bin/{{ item }}"
    state: link
  with_items: "{{ kubernetes_binaries }}"
  tags: 
    - kubernetes
    - kubernetes-common
