#
#   Author: Rohith
#   Date: 2015-04-22 15:20:26 +0100 (Wed, 22 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---
etcd_version: v2.0.3
etcd_release: https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
etcd_servers_group: etcd_servers

