#
#   Author: Rohith
#   Date: 2015-04-24 15:22:49 +0100 (Fri, 24 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
---

provider: vcloud
environment: dev
dns_zone: example.com
dns_region: dev
dns_base: "{{ dns_region }}.{{ dns_zone }}"
dns_ttl: 90
dns_servers:
  - 8.8.8.8
  - 8.8.4.4
timezone: UTC
ntp_servers:
  - 0.uk.pool.ntp.org
  - 1.uk.pool.ntp.org
  - 2.uk.pool.ntp.org
  - 3.uk.pool.ntp.org

## HOSTS
managed_hosts:
  - name: "bastion101.{{ dns_base }}"
    ip_address: 10.7.20.11
  - name: "gluster101.{{ dns_base }}"
    ip_address: 10.7.20.5
  - name: "gluster102.{{ dns_base }}"
    ip_address: 10.7.20.6
  - name: "core101.{{ dns_base }}"
    ip_address: 10.7.20.101
  - name: "core102.{{ dns_base }}"
    ip_address: 10.7.20.102
  - name: "core103.{{ dns_base }}"
    ip_address: 10.7.20.103

## BASTION
bastion_pubkey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDoZ8+Oz2YLPklKGcEChFQeYJU6IEje3rJ0jUB3BJdTUJIbhUS8/1dGDXUTLWoM/7UrCBztFo5zH9E1wP1G6HwwRBwt48xVCr7bxLyTokr0hsfIRIf8NpnAnRTV+ltXcViqur9LsXEq07IAKP8QxJcECC3uzEFlHEmOu7lRcWa+SPv7sYv7KJ3BDXsAs/maVy19vWtVqkWdPtZepnO3xc0atJWOmNWn1T5tuc5NPIsep3VtsjqGrkuq6sE1npIqkFl0QDZCc25F5AFlEtNHZa3IYg3q6D76N9+qdGqvEpaRlXYuCA+TBONiVu+WpuouiMu9UycK+VFLzFdOgA/Fzfvf jest@starfury
  
## DHCP
dhcpd:
  subnets:
    - network: 10.7.20.0
      netmask: 255.255.255.0
      router: 10.7.20.1
      domain: "{{ dns_base }}"
      dns_servers: "{{ dns_servers }}"
      range_start: 10.7.20.101
      range_end: 10.7.20.199
      hosts:
        - name: "core101.{{ dns_base }}"
          mac: 00:02:0a:07:14:65
          ip_address: 10.7.20.101
        - name: "core102.{{ dns_base }}"
          mac: 00:02:0a:07:14:66
          ip_address: 10.7.20.102
        - name: "core103.{{ dns_base }}"
          mac: 00:02:0a:07:14:67
          ip_address: 10.7.20.103 
        - name: "core104.{{ dns_base }}"
          mac: 00:02:0a:07:14:68
          ip_address: 10.7.20.104

## ETCD
discovery_service: https://discovery.etcd.io
discovery_token: 0ec322878b65980d2539f23cf7018da5

## KUBERNETES ============================
kubernetes_overlay_network: 10.101.0.0
kubernetes_overlay_prefix: 16
kubernetes_subnets: 24
kubernetes_subnets_min: 10.101.1.0
kubernetes_subnets_max: 10.101.50.0
kubernetes_backend: vxlan
kubernetes_master_group: kubernetes_master
kubernetes_minion_group: kubernetes_minion
kubernetes_etcd_group: kubernetes_minion
kubernetes_master_name: "{{ groups['kubernetes_master'][0] }}"
kubernetes_master_ipaddress: "{{ hostvars[kubernetes_master_name].ansible_default_ipv4.address }}"
kubernetes_master_group: kubernetes_master
kubernetes_minion_servers: "{% for host in groups[kubernetes_minion_group] %}{{ hostvars[host].ansible_default_ipv4.address }}{% if not loop.last %},{% endif %}{% endfor %}"

## FLANNEL 
flannel_overlay_network: "{{ kubernetes_overlay_network }}"
flannel_overlay_prefix:  "{{ kubernetes_overlay_prefix }}"
flannel_subnets: "{{ kubernetes_subnets }}"
flannel_subnets_min: "{{ kubernetes_subnets_min }}"
flannel_subnets_max: "{{ kubernetes_subnets_max }}"
flannel_backend: "{{ kubernetes_backend }}"
flannel_etcd_group: kubernetes_minion
flannel_config_group: kubernetes_minion

## GLUSTERFS
gluster_server_group: glusterfs_servers
gluster_mounted_volumes: []

## FLEET
fleet_deployed: true
fleet_delegation: "bastion101.{{ dns_base }}"
fleet_endpoints: "{% for host in groups[kubernetes_minion_group] %}http://{{ host }}:4001{% if not loop.last %},{% endif %}{% endfor %}"
