#
#   Author: Rohith
#   Date: 2015-05-05 23:30:30 +0100 (Tue, 05 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: creating the yum repository directory
  sudo: yes
  file: path=/var/lib/yum state=directory mode=0770

- name: add yum mirror service
  sudo: yes
  template:
    src: yum-mirror.service.j2
    dest: "{{ systemd_dir }}/yum-mirror.service"
  notify:
    - reload services
    - restart yum mirror
  tags:
    - yum
    - yum-mirror

- name: ensure the yum mirror service
  sudo: yes
  service: name=yum-mirror state=started enabled=yes

