#
#   Author: Rohith
#   Date: 2015-05-03 15:29:08 +0100 (Sun, 03 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the kubelet fleet unit
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  template: 
    src:  kubernetes-kubelet.service.j2
    dest: /config/kubernetes/kubernetes-kubelet.service
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-kubelet

- name: starting the kubelet service via fleet
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  shell: fleetctl start /config/kubernetes/kubernetes-kubelet.service
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-kubelet
