#
#   Author: Rohith
#   Date: 2015-06-01 20:27:16 +0100 (Mon, 01 Jun 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the kubelet proxy fleet unit
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  template: 
    src:  kubernetes-proxy.service.j2
    dest: /config/kubernetes/kubernetes-proxy.service
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-proxy

- name: starting the kubelet proxy via fleet
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  sudo: yes
  shell: fleetctl start /config/kubernetes/kubernetes-proxy.service
  register: result
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-proxy

