#
#   Author: Rohith
#   Date: 2015-05-03 15:29:02 +0100 (Sun, 03 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the kubelet fleet unit
  template: 
    src:  kubernetes-proxy.service.j2
    dest: /config/kubernetes/kubernetes-proxy.service
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-proxy
  when: fleet_deployed

- name: starting the kubelet service via fleet
  delegate_to: "{{ kubernetes_master_hostname }}"
  fleet: 
    command: start
    endpoint: "http://{{ kubernetes_master_hostname }}:4001"
    unit: /config/kubernetes/kubernetes-proxy.service
  register: result
  failed_when: result.msg != 'OK'
  changed_when: result.msg != 'OK'
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-proxy
  when: fleet_deployed

- name: adding the kubernetes proxy service
  template: src=kubernetes-proxy.service.j2 dest={{ systemd_dir }}/kubernetes-proxy.service 
  notify: 
    - reload services
    - restart kubernetes proxy 
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-proxy
  when: fleet_deployed == false

- name: start the kubernetes proxy service
  service: name=kubernetes-proxy state=started enabled=yes
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-proxy
  when: fleet_deployed == false
