#
#   Author: Rohith
#   Date: 2015-06-01 20:28:04 +0100 (Mon, 01 Jun 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: create the kube-register fleet unit
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  sudo: yes
  template: 
    src:  kubernetes-router.service.j2
    dest: /config/kubernetes/kubernetes-router.service
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-router

- name: starting the kubernetes-router via fleet
  run_once: true
  delegate_to: "{{ fleet_delegation }}"
  sudo: yes
  fleet: 
    command: start 
    unit: /config/kubernetes/kubernetes-proxy.service
  tags: 
    - kubernetes
    - kubernetes-minion
    - kubernetes-router
