#
#   Author: Rohith
#   Date: 2015-05-23 12:09:44 +0100 (Sat, 23 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

- name: creating the data directory
  sudo: yes
  file: path={{ fleet_dir }} state=directory mode=0770
  tags: fleet

- name: downloading the fleetd binaries
  sudo: yes
  get_url:
    url: "{{ fleet_url }}"
    dest: /opt/fleet.tar.gz
    mode: 0400
  tags: fleet

- stat: path="/opt/fleet-{{ fleet_version }}-linux-amd64"
  register: extracted
  tags: fleet

- name: extracting the fleet binaries
  sudo: yes
  unarchive:
    src: /opt/fleet.tar.gz
    dest: /opt
    copy: no
  when: extracted.stat.exists == False
  tags: fleet

- name: create a fleet distribution links
  sudo: yes
  file:
    src: "/opt/fleet-{{ fleet_version }}-linux-amd64/{{ item }}"
    dest: "/opt/fleet/{{ item }}"
    state: link
  with_items:
    - fleetd
    - fleetctl
  tags: fleet
